# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22926ad1624673987e047e9e8844ef7ee353891f0f53fa84f9783089bad8c3de1f99cd6977b35437490c705130989a1d2dd411b0ba77b662448fd5c40bd08c85

test:
  secret_key_base: 9cf5c78288b96e751acd3959ebf35b1c996328c8b249beb3a2ca027d5c467f5812b3356d963e327ec28d4fc6ba56545a2c5fa14538f44062f57346dfad19025a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
